server:
  port: 8080

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8099/eureka/

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: demo-services-client
          uri: lb://demo-services-client
          predicates:
              - Path=/clientes/**
        - id: demo-services-product
          uri: lb://demo-services-product
          predicates:
            - Path=/productos/**
        - id: demo-services-shopping
          uri: lb://demo-services-shopping
          predicates:
            - Path=/facturas/**