server:
  port: 8081

spring:
  application:
    name: configserver
  cloud:
    config:
      enable: true
      server:
        git:
          default-label: main
          uri: https://github.com/george1002jlbb/demo-microservices.git
          searchPaths: config-data
          username: george1002jlbb
          password: Sqweasdzxc1234$
  security:
    user:
      name: user
      password: s3cr3t